# Generated by Django 3.1.7 on 2021-03-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True, max_length=128),
        ),
    ]
